config/routes.rb
require 'sidekiq/web'

Lagotto::Application.routes.draw do
  # mount EmberCLI::Engine => "ember-tests" if Rails.env.development?

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  #root :to => "ember#index"
  #get '/docs/*path' => 'ember#index'

  # simplify GET route to works
  #get '/:id', to: 'works#show', constraints: { id: /(http|https):\/\/.+/, format: /html/ }
  root :to => "docs#index"

  resources :alerts
  resources :api_requests
  resources :docs, :only => [:index, :show], :constraints => { :id => /[0-z\-\.\(\)]+/ }
  resources :filters
  resources :publishers
  resources :references

  # use namespace for rss feeds rather than file extension
  namespace :rss, defaults: { format: "rss" } do
    resources :works, constraints: { :id => /.+/ }, only: [:show]
    resources :sources, only: [:show]
  end

  # redirect old rss routes
  get '/sources/:id.rss', to: redirect { |params, request| "/rss/sources/#{request.params[:id]}?#{request.params.to_query}" }

  resources :sources do
    resources :publisher_options, only: [:show, :edit, :update]
  end
  resources :status, :only => [:index]
  resources :users

  # constraints is added to allow dot in the url (doi is used to show article)
  resources :works, constraints: { :id => /.+/, :format => /html|js/ }

  get "oembed", to: "oembed#show"

  get "/files/alm_report.zip", to: redirect("/files/alm_report.zip")
  get "/api", to: "api/index#index"

  namespace :api, defaults: { format: "json" } do
    namespace :v3 do
      resources :works, path: "articles", constraints: { :id => /.+?/, :format=> false }, only: [:index, :show]
    end

    namespace :v5 do
      resources :works, path: "articles", constraints: { :id => /.+?/ }, only: [:index]
      resources :sources, only: [:index, :show]
      resources :status, only: [:index]
      resources :api_requests, only: [:index]
      resources :publishers, only: [:index]
    end

    scope module: :v6, constraints: ApiConstraint.new(version: 6, default: :true) do
      concern :workable do
        resources :works, constraints: { :id => /.+?/, format: false }
      end

      concern :eventable do
        resources :events
      end

      resources :alerts
      resources :api_requests, only: [:index]
      resources :docs, only: [:index, :show]
      resources :events
      resources :groups, only: [:index, :show]
      resources :publishers, concerns: [:workable, :eventable]
      resources :references
      resources :relation_types, only: [:index, :show]
      resources :sources, concerns: [:workable, :eventable] do
        resources :months
      end
      resources :status, only: [:index]
      resources :work_types, only: [:index, :show]
      resources :works, constraints: { :id => /.+?/, :format=> false } do
        resources :references
        resources :versions
        resources :recommendations
        resources :events
      end
    end
  end

  # rescue routing errors
  match "*path", to: "alerts#routing_error", via: [:any]
end

app/models/source.rb
require 'cgi'
require "addressable/uri"

class Source < ActiveRecord::Base
  # include state machine
  include Statable

  # include default methods for subclasses
  include Configurable

  # include methods for calculating metrics
  include Measurable

  # include HTTP request helpers
  include Networkable

  # include CouchDB helpers
  include Couchable

  # include author methods
  include Authorable

  # include date methods
  include Dateable

  # include DOI helper methods
  include Resolvable

  # include summary counts
  include Countable

  # include hash helper
  include Hashie::Extensions::DeepFetch

  BLANK_FIELDS = { "crossref" => [:username, :password, :openurl_username],
                   "pmc" => [:journals, :username, :password],
                   "facebook" => [:client_id, :client_secret, :url_linkstat, :access_token],
                   "mendeley" => [:access_token],
                   "twitter_search" => [:access_token],
                   "scopus" => [:insttoken] }

  has_many :retrieval_statuses, :dependent => :destroy
  has_many :months
  has_many :days
  has_many :works, :through => :retrieval_statuses
  has_many :publishers, :through => :publisher_options
  has_many :publisher_options
  has_many :alerts
  has_many :api_responses
  has_many :reference_relations
  has_many :version_relations
  belongs_to :group

  serialize :config, OpenStruct

  validates :name, :presence => true, :uniqueness => true
  validates :title, :presence => true
  validates :timeout, :numericality => { :only_integer => true, :greater_than => 0 }
  validates :max_failed_queries, :numericality => { :only_integer => true, :greater_than => 0 }
  validates :rate_limiting, :numericality => { :only_integer => true, :greater_than => 0 }
  validates :staleness_week, :numericality => { :only_integer => true, :greater_than => 0 }
  validates :staleness_month, :numericality => { :only_integer => true, :greater_than => 0 }
  validates :staleness_year, :numericality => { :only_integer => true, :greater_than => 0 }
  validates :staleness_all, :numericality => { :only_integer => true, :greater_than => 0 }
  validate :validate_cron_line_format, if: Proc.new { |source| source.cron_line.present? }

  # filter sources by state
  scope :by_state, ->(state) { where("state = ?", state) }
  scope :by_states, ->(state) { where("state > ?", state) }
  scope :order_by_title, -> { order("group_id, sources.title") }

  scope :available, -> { by_state(0).order_by_title }
  scope :retired, -> { by_state(1).order_by_title }
  scope :inactive, -> { by_state(2).order_by_title }
  scope :disabled, -> { by_state(3).order_by_title }
  scope :waiting, -> { by_state(5).order_by_title }
  scope :working, -> { by_state(6).order_by_title }

  scope :installed, -> { by_states(0).order_by_title }
  scope :visible, -> { by_states(1).order_by_title }
  scope :active, -> { by_states(2).order_by_title }

  scope :for_events, -> { active.where("name != ?", 'relativemetric') }
  scope :queueable, -> { active.where(queueable: true) }
  scope :eventable, -> { visible.where(eventable: true) }

  scope :without_private, -> { where(private: false) }

  # some sources cannot be redistributed
  scope :accessible, ->(role) { where("private <= ?", role) }

  def to_param  # overridden, use name instead of id
    name
  end

  def remove_queues
    # delete_jobs(name)
    retrieval_statuses.update_all(queued_at: nil)
  end

  def queue_all_works(options = {})
    return 0 unless active?

    # find works that need to be updated.
    # Tracked, not queued currently, scheduled_at doesn't matter
    rs = retrieval_statuses.tracked

    # optionally limit to works scheduled_at in the past
    rs = rs.stale unless options[:all]

    # optionally limit by publication date
    if options[:start_date] && options[:end_date]
      rs = rs.joins(:work).where("works.published_on" => options[:start_date]..options[:end_date])
    end

    rs = rs.order("retrieval_statuses.id").pluck("retrieval_statuses.id")
    count = queue_work_jobs(rs)
  end

  def queue_work_jobs(rs, options = {})
    return 0 unless active?

    if rs.length == 0
      wait
      return 0
    end

    rs.each_slice(job_batch_size) do |rs_ids|
      RetrievalStatus.where("id in (?)", rs_ids).update_all(queued_at: Time.zone.now)
      SourceJob.set(queue: queue, wait_until: schedule_at).perform_later(rs_ids, self)
    end

    rs.length
  end

  def schedule_at
    last_response + batch_interval
  end

  # disable source if more than max_failed_queries (default: 200) in 24 hrs
  def check_for_failures
    failed_queries = Alert.where("source_id = ? AND level > 1 AND updated_at > ?", id, Time.zone.now - max_failed_query_time_interval).count
    failed_queries > max_failed_queries
  end

  # disable source if rate_limiting reached
  def check_for_rate_limits
    rate_limit_remaining < 10
  end

  # calculate wait time until next API call
  # wait until reset time if rate-limiting limit is close
  def wait_time
    if rate_limit_remaining < 50
      [rate_limit_reset - Time.zone.now, 0.001].sort.last
    else
      3600.0 / rate_limiting
    end
  end

  def get_data(work, options={})
    query_url = get_query_url(work)
    return query_url.extend Hashie::Extensions::DeepFetch if query_url.is_a?(Hash)

    result = get_result(query_url, options.merge(request_options))

    # make sure we return a hash
    result = { 'data' => result } unless result.is_a?(Hash)

    # extend hash fetch method to nested hashes
    result.extend Hashie::Extensions::DeepFetch
  end

  def parse_data(result, work, options = {})
    if !result.is_a?(Hash)
      # make sure we have a hash
      result = { 'data' => result }
      result.extend Hashie::Extensions::DeepFetch
    elsif result[:status] == 404
      # properly handle not found errors
      result = { 'data' => [] }
      result.extend Hashie::Extensions::DeepFetch
    elsif result[:error]
      # return early if an error occured that is not a not_found error
      return result
    end

    related_works = get_related_works(result, work)
    extra = get_extra(result)
    events_url = related_works.length > 0 ? get_events_url(work) : nil

    options.merge!(response_options)
    options[:metrics] ||= :total
    metrics = get_metrics(options[:metrics] => related_works.length)

    { works: related_works,
      events: {
        source: name,
        work: work.pid,
        pdf: metrics[:pdf],
        html: metrics[:html],
        readers: metrics[:readers],
        comments: metrics[:comments],
        likes: metrics[:likes],
        total: metrics[:total],
        events_url: events_url,
        extra: extra,
        days: get_events_by_day(related_works, work, options),
        months: get_events_by_month(related_works, options) }.compact }
  end

  def get_events_by_day(events, work, options={})
    events = events.reject { |event| event["timestamp"].nil? || Date.iso8601(event["timestamp"]) - work.published_on > 30 }

    options[:metrics] ||= :total
    events.group_by { |event| event["timestamp"][0..9] }.sort.map do |k, v|
      { year: k[0..3].to_i,
        month: k[5..6].to_i,
        day: k[8..9].to_i,
        options[:metrics] => v.length,
        total: v.length }
    end
  end

  def get_events_by_month(events, options={})
    events = events.reject { |event| event["timestamp"].nil? }

    options[:metrics] ||= :total
    events.group_by { |event| event["timestamp"][0..6] }.sort.map do |k, v|
      { year: k[0..3].to_i,
        month: k[5..6].to_i,
        options[:metrics] => v.length,
        total: v.length }
    end
  end

  def get_extra(result)
    nil
  end

  def request_options
    {}
  end

  def response_options
    {}
  end

  def get_query_url(work, options = {})
    fail ArgumentError, "Source url is missing." if url.blank?

    query_string = get_query_string(work)
    return query_string if query_string.is_a?(Hash)

    url % { query_string: query_string }
  end

  def get_events_url(work)
    fail ArgumentError, "Source events_url is missing." if events_url.blank?

    query_string = get_query_string(work)
    return query_string if query_string.is_a?(Hash)

    events_url % { query_string: query_string }
  end

  def get_query_string(work)
    return {} unless work.get_url || work.doi.present?

    [work.doi, work.canonical_url].compact.map { |i| "%22#{i}%22" }.join("+OR+")
  end

  # fields with urls, not user-configurable
  def url_fields
    config_fields.select { |field| field =~ /url\z/ }
  end

  # fields with publisher-specific settings such as API keys,
  # i.e. everything that is not a URL
  def publisher_fields
    config_fields.select { |field| field !~ /url/ }
  end

  # all other fields
  def other_fields
    config_fields.select { |field| field =~ /url.+/ }
  end

  # all publisher-specific configurations
  def publisher_configs
    return [] unless by_publisher?

    publisher_options.pluck(:publisher_id, :config)
  end

  def publisher_config(publisher_id)
    conf = publisher_configs.find { |conf| conf[0] == publisher_id }
    conf.nil? ? OpenStruct.new : conf[1]
  end

  def allowed_blank_fields
    BLANK_FIELDS.fetch(name, [])
  end

  # Custom validations that are triggered in state machine
  def validate_config_fields
    config_fields.each do |field|

      # Some fields can be blank
      next if allowed_blank_fields.include?(field)
      errors.add(field, "can't be blank") if send(field).blank?
    end
  end

  # Custom validation for cron_line field
  def validate_cron_line_format
    cron_parser = CronParser.new(cron_line)
    cron_parser.next(Time.zone.now)
  rescue ArgumentError
    errors.add(:cron_line, "is not a valid crontab entry")
  end

  # import couchdb data for lagotto 4.0 upgrade
  def import_from_couchdb
    return 0 unless active?

    # find works that need to be imported.
    rs = retrieval_statuses

    rs = rs.order("retrieval_statuses.id").pluck("retrieval_statuses.id")
    count = queue_import_jobs(rs)

app/models/sources/ads.rb
class Ads < Source
  # include common methods for Article Coverage
  include Adsable

  def get_query_string(work)
    if work.doi.present?
      "\"doi:#{work.doi}\""
    else
      {}
    end
  end

  def get_related_works(result, work)
    result["response"] ||= {}
    Array(result["response"]["docs"]).map do |item|
      arxiv = item.fetch("identifier", []).find { |i| i =~ ARXIV_FORMAT }
      next unless arxiv.present?

      arxiv = arxiv.gsub(/\A\D*(\d{4}\.\d{4,5})D*/, '\1')

      { "author" => get_authors(item.fetch('author', []), reversed: true, sep: ", "),
        "title" => item.fetch("title", []).first.chomp("."),
        "container-title" => "ArXiV",
        "issued" => get_date_parts(item.fetch("pubdate", nil)),
        "URL" => "http://arxiv.org/abs/#{arxiv}",
        "arxiv" => arxiv,
        "type" => "article-journal",
        "tracked" => tracked,
        "related_works" => [{ "related_work" => work.pid,
                              "source" => name,
                              "relation_type" => "is_previous_version_of" }] }
    end.compact
  end

  def url
    "https://api.adsabs.harvard.edu/v1/search/query?"
  end

  def events_url
    "https://ui.adsabs.harvard.edu/#search/q=body:%{query_string}"
  end

  def rate_limiting
    config.rate_limiting || 1000
  end

  def queue
    config.queue || "low"
  end
end

app/models/sources/ads_fulltext.rb
class AdsFulltext < Source
  # include common methods for Article Coverage
  include Adsable

  def get_query_string(work)
    if work.doi.present?
      "\"body:#{work.doi}\""
    elsif work.canonical_url.present?
      "\"body:#{work.canonical_url}\""
    else
      {}
    end
  end

  def get_related_works(result, work)
    result["response"] ||= {}
    Array(result["response"]["docs"]).map do |item|
      arxiv = item.fetch("identifier", []).find { |i| i.starts_with?("arXiv:") }
      next unless arxiv.present?

      arxiv = arxiv.gsub(/\A\D*(\d{4}\.\d{4,5})D*/, '\1')

      { "author" => get_authors(item.fetch('author', []), reversed: true, sep: ", "),
        "title" => item.fetch("title", []).first.chomp("."),
        "container-title" => "ArXiV",
        "issued" => get_date_parts(item.fetch("pubdate", nil)),
        "URL" => "http://arxiv.org/abs/#{arxiv}",
        "arxiv" => arxiv,
        "type" => "article-journal",
        "tracked" => tracked,
        "related_works" => [{ "related_work" => work.pid,
                              "source" => name,
                              "relation_type" => "cites" }] }
    end.compact
  end

  def url
    "https://api.adsabs.harvard.edu/v1/search/query?"
  end

  def events_url
    "https://ui.adsabs.harvard.edu/#search/q=body:%{query_string}"
  end

  def rate_limiting
    config.rate_limiting || 1000
  end

  def queue
    config.queue || "low"
  end
end

app/models/sources/article_coverage.rb
class ArticleCoverage < Source
  # include common methods for Article Coverage
  include Coverable

  def parse_data(result, work, options = {})
    if !result.is_a?(Hash)
      # make sure we have a hash
      result = { 'data' => result }
      result.extend Hashie::Extensions::DeepFetch
    elsif result[:status] == 404
      # properly handle not found errors
      result = { 'data' => [] }
      result.extend Hashie::Extensions::DeepFetch
    elsif result[:error]
      # return early if an error occured that is not a not_found error
      return result
    end

    extra = get_extra(result)
    metrics = get_metrics(comments: extra.length)

    { events: {
        source: name,
        work: work.pid,
        comments: metrics[:comments],
        total: metrics[:total],
        extra: extra } }
  end

  def get_extra(result)
    Array(result['referrals']).map do |item|
      { event: item,
        event_time: get_iso8601_from_time(item['published_on']),
        event_url: item['referral'] }
    end
  end
end

app/models/sources/biod.rb
class Biod < Source
  def obsolete?
    true
  end
end

app/models/sources/bloglines.rb
class Bloglines < Source
  def obsolete?
    true
  end
end

app/models/sources/connotea.rb
class Connotea < Source
  def obsolete?
    true
  end
end

app/views/sources/_configuration.html.erb
<div class="panel panel-default">
  <div class="panel-heading panel-title">
    <% if can?(:manage, Source) && @source.state > 1 && controller.action_name != "edit" && !(controller.action_name == "update" && !@source.errors.empty?) %>
      <div class="btn-toolbar pull-right">
        <div class="btn-group btn-group-sm">
          <%= link_to icon("pencil").html_safe, edit_source_path(@source.name), { :remote => true, :class => 'btn btn-default btn-sm pull-right configuration-edit', :title => "Edit" } %>
        </div>
      </div>
    <% end %>
    Configuration
  </div>
  <% if can?(:manage, Source) && @source.state > 1 && (controller.action_name == "edit" || (controller.action_name == "update" && !@source.errors.empty?)) %>
    <div class="panel-body">
      <%= simple_form_for(@source.becomes(Source), :url => source_path(@source.name), :html => { :remote => true }) do |f| %>
        <% f.object = @source.becomes(@source.class) %>

        <%= f.input :title %>
        <%= f.input :state_event, :as => :boolean, label: "Active", :checked_value => 'activate', :unchecked_value => 'inactivate', input_html: { checked: @source.active? }, hint: "Source is talking to external APIs" %>
        <%= f.input :private, :as => :boolean, hint: "Source not made available via API" %>
        <% if @source.eventable %>
          <%= f.input :tracked, :as => :boolean, hint: "Track events for works added via this source" %>
        <% end %>
        <%= f.input :description, :input_html => { :rows => 3 } %>

        <% @source.other_fields.each do |field| %>
          <%= f.input field %>
        <% end %>

        <% unless @source.by_publisher? %>
          <% @source.publisher_fields.each do |field| %>
            <% if field == "password" %>
              <%= f.input field, :as => :string %>
            <% elsif field == "expires_at" %>
              <%= f.input field, :as => :hidden %>
            <% else %>
              <%= f.input field %>
            <% end %>
          <% end %>
        <% end %>

        <%= f.input :queue,             collection: QUEUE_OPTIONS,
                                        label: "Job queue",
                                        include_blank: false,
                                        hint: "Job queue for workers" %>
        <%= f.input :rate_limiting, :as => :numeric, label: false,
                                                      hint: "Max. requests per hour" %>
        <% if @source.queueable %>
          <%= f.input :staleness_week,  collection: INTERVAL_OPTIONS,
                                        label: "Update interval",
                                        include_blank: false,
                                        hint: "First 7 days after publication" %>
          <%= f.input :staleness_month, collection: INTERVAL_OPTIONS,
                                        label: false,
                                        include_blank: false,
                                        hint: "First 31 days after publication" %>
          <%= f.input :staleness_year,  collection: INTERVAL_OPTIONS,
                                        label: false,
                                        include_blank: false,
                                        hint: "First year after publication" %>
          <%= f.input :staleness_all,   collection: INTERVAL_OPTIONS,
                                        label: false,
                                        include_blank: false,
                                        hint: "More than one year after publication" %>
        <% else %>
          <%= f.input :cron_line, label: "Update interval",
                                  hint: "Time in crontab format before more jobs can be added to the job queue" %>
        <% end %>

        <%= f.input :timeout, hint: "Time to wait for response from the source (seconds)"  %>

        <%= f.input :max_failed_queries, label: "Failed queries",
                                         hint: "Maximum number of failed queries allowed per 24 hours before being disabled" %>

        <div class="form-group">
          <%= f.submit "Save ", class: "btn btn-default" %>
          <%= link_to 'Cancel', source_path(@source.name), { :remote => true, :class => 'btn' } %>
        </div>
      <% end %>
    </div>
  <% else %>
    <table class="table" id="ConfigurationTable">
      <tbody>
        <% @source.url_fields.each do |field| %>
          <tr>
            <th><%= field.to_s.gsub(/_/, " ").capitalize %></th>
            <td><%= @source.send(field) %></td>
          </tr>
        <% end %>
        <% @source.other_fields.each do |field| %>
          <tr>
            <th><%= field.to_s.gsub(/_/, " ").capitalize %></th>
            <td><%= @source.send(field) %></td>
          </tr>
        <% end %>
        <% unless @source.by_publisher? %>
          <% @source.publisher_fields.each do |field| %>
            <tr>
              <th><%= field.to_s.gsub(/_/, " ").capitalize %></th>
              <% if [:username, :password, :client_id, :secret, :access_token, :api_key].include?(field) && cannot?(:manage, Source) %>
                <td><em>hidden</em></td>
              <% else %>
                <td><%= @source.send(field) %></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
        <% if @source.private %>
          <tr>
            <th>Private source</th>
            <td>Source not made available via API</td>
          </tr>
        <% end %>
        <% if @source.tracked %>
          <tr>
            <th>Track works</th>
            <td>Track events for works added via this source</td>
          </tr>
        <% end %>
        <tr>
          <th>Job queue</th>
          <td>
            <%= @source.rate_limiting %> per hour rate-limiting</br>
            <%= @source.rate_limit_remaining %> remaining to rate-limit</br>
            rate-limiting reset at <%= @source.rate_limit_reset.to_formatted_s(:long) %> UTC</br>
            job queue <%= @source.queue %>
          </td>
        </tr>
        <tr>
          <th>Update interval</th>
          <% if @source.queueable %>
            <td><%= @source.staleness_with_limits.map { |i, j| distance_of_time(j) + " for works published #{i}" }.join("</br>").html_safe %></td>
          <% else %>
            <td>Next update <%= @source.cron_line ? CronParser.new(@source.cron_line).next(Time.zone.now).to_s(:short) + " UTC" : "N/A" %></td>
          <% end %>
        </tr>
        <tr>
          <th>Timeout</th>
          <td><%=h @source.timeout %> seconds wait time for response from the source</td>
        </tr>
        <tr>
          <th>Failed queries</th>
          <td>
            <%= @source.max_failed_queries %> failed queries allowed per 24 hours before source is disabled</br>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/sources/_events.html.erb
<% if Work.first && Source.visible.any? %>
  <div class="panel panel-default">
    <div class="panel-heading panel-title">Works with events<small class="pull-right">linear scale</small></div>
    <div class="panel-body" id="work-body">
      <div class="text-muted" id="work-loading">Loading … <%= image_tag "spinner.gif" %></div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading panel-title">Total number of events <small class="pull-right">logarithmic scale</small></div>
    <div class="panel-body" id="event-body">
      <div class="text-muted" id="event-loading">Loading … <%= image_tag "spinner.gif" %></div>
    </div>
  </div>
<% else %>
  <div class="alert alert-info">No events found</div>
<% end %>

<%= javascript_include_tag 'sources/index' %>

app/views/sources/_installation.html.erb
<% if @groups.size > 0 %>
  <% @groups.with_sources.each do |group| %>
    <div class="panel panel-default">
      <div class="panel-heading"><%= group.title %></div>
      <table class="table" id="<%= group.title %>Table">
        <thead>
          <tr>
            <th class="name">Source</th>
            <th>Status</th>
            <th class="description">Description</th>
            <% if can?(:manage, Alert) %>
              <th class="status">Actions</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% group.sources.each do |source| %>
            <tr>
              <td><%= link_to_if source.installed?, source.title, source_path(source) %></td>
              <td><%= state_label(source.human_state_name).html_safe %></td>
              <td><%= h(source.description) %></td>
              <% if can?(:manage, Alert) %>
                <td>
                  <% if source.human_state_name == "available" %>
                    <%= link_to 'Install', source_path(source, state_event: "install"), :method => :put, :data => { :confirm => 'Are you sure?' }, :remote => true, :class => 'btn btn-default btn-sm', :id => "#{source.name}-status", :title => "Install Source" %>
                  <% elsif source.human_state_name == "retired" %>
                  <% elsif source.human_state_name == "inactive" %>
                    <%= link_to 'Activate', source_path(source, state_event: "activate"), :method => :put, :remote => true, :class => 'btn btn-success btn-sm', :id => "#{source.name}-status", :title => "Activate Source" %>
                  <% else %>
                    <%= link_to 'Inactivate', source_path(source, state_event: "inactivate"), :method => :put, :remote => true, :class => 'btn btn-info btn-sm', :id => "#{source.name}-status", :title => "Inactivate Source" %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% else %>
  <div class="alert alert-info">There are currently no groups</div>
<% end %>

app/views/sources/_responses.html.erb
<% unless Source.visible.empty? %>
  <% @groups.visible.each do |group| %>
    <div class="panel panel-default">
      <div class="panel-heading"><%= group.title %></div>
      <table class="table" id="<%= group.title %>Table">
        <thead>
          <tr>
            <th class="name">Source</th>
            <th>Status</th>
            <th class="number">Responses&nbsp;(24&nbsp;hours)</th>
            <th class="number">Average&nbsp;(ms)</th>
            <th class="number">Errors (24&nbsp;hours)</th>
          </tr>
        </thead>
        <tbody>
          <% group.sources.visible.each do |source| %>
            <tr>
              <td><%= link_to source.title, source_path(source) %></td>
              <td><%= state_label(source.human_state_name).html_safe %></td>
              <td class="number" id="response_count_<%= source.name %>"></td>
              <td class="number" id="average_count_<%= source.name %>"></td>
              <td class="number" id="error_count_<%= source.name %>"><%= source.error_count > 0 ? link_to(number_hiding_zero(source.error_count), alerts_path(source_id: source.name)) : "" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% else %>
  <div class="alert alert-info">No active sources found</div>
<% end %>

app/views/sources/_summary.html.erb
<% unless Source.visible.empty? %>
  <% @groups.visible.each do |group| %>
    <div class="panel panel-default">
      <div class="panel-heading"><%= group.title %></div>
      <table class="table" id="<%= group.title %>Table">
        <thead>
          <tr>
            <th class="name">Source</th>
            <th>Status</th>
            <th class="description">Description</th>
            <% if can?(:read, Alert) %>
              <th class="number">Queued&nbsp;Works</th>
              <th class="number">Stale&nbsp;Works</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% group.sources.visible.each do |source| %>
            <tr>
              <td><%= link_to source.title, source_path(source) %></td>
              <td><%= state_label(source.human_state_name).html_safe %></td>
              <td><%= h(source.description) %></td>
              <% if can?(:read, Alert) %>
                <td class="number" id="queued_count_<%= source.name %>"></td>
                <td class="number" id="stale_count_<%= source.name %>"></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% else %>
  <div class="alert alert-info">No active sources found</div>
<% end %>

app/views/sources/_works.html.erb
<div id="rss" class="pull-right">
  <%= link_to image_tag("feed-icon-28x28.png"), rss_source_path(@source) %>
</div>

<div class="content" id="content">
  <div class="text-muted" id="loading-results">Loading … <%= image_tag "spinner.gif" %></div>
</div>

<%= javascript_include_tag 'works/index' %>