config/routes.rb
require 'sidekiq/web'

Lagotto::Application.routes.draw do
  # mount EmberCLI::Engine => "ember-tests" if Rails.env.development?

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  #root :to => "ember#index"
  #get '/docs/*path' => 'ember#index'

  # simplify GET route to works
  #get '/:id', to: 'works#show', constraints: { id: /(http|https):\/\/.+/, format: /html/ }
  root :to => "docs#index"

  resources :alerts
  resources :api_requests
  resources :docs, :only => [:index, :show], :constraints => { :id => /[0-z\-\.\(\)]+/ }
  resources :filters
  resources :publishers
  resources :references

  # use namespace for rss feeds rather than file extension
  namespace :rss, defaults: { format: "rss" } do
    resources :works, constraints: { :id => /.+/ }, only: [:show]
    resources :sources, only: [:show]
  end

  # redirect old rss routes
  get '/sources/:id.rss', to: redirect { |params, request| "/rss/sources/#{request.params[:id]}?#{request.params.to_query}" }

  resources :sources do
    resources :publisher_options, only: [:show, :edit, :update]
  end
  resources :status, :only => [:index]
  resources :users

  # constraints is added to allow dot in the url (doi is used to show article)
  resources :works, constraints: { :id => /.+/, :format => /html|js/ }

  get "oembed", to: "oembed#show"

  get "/files/alm_report.zip", to: redirect("/files/alm_report.zip")
  get "/api", to: "api/index#index"

  namespace :api, defaults: { format: "json" } do
    namespace :v3 do
      resources :works, path: "articles", constraints: { :id => /.+?/, :format=> false }, only: [:index, :show]
    end

    namespace :v5 do
      resources :works, path: "articles", constraints: { :id => /.+?/ }, only: [:index]
      resources :sources, only: [:index, :show]
      resources :status, only: [:index]
      resources :api_requests, only: [:index]
      resources :publishers, only: [:index]
    end

    scope module: :v6, constraints: ApiConstraint.new(version: 6, default: :true) do
      concern :workable do
        resources :works, constraints: { :id => /.+?/, format: false }
      end

      concern :eventable do
        resources :events
      end

      resources :alerts
      resources :api_requests, only: [:index]
      resources :docs, only: [:index, :show]
      resources :events
      resources :groups, only: [:index, :show]
      resources :publishers, concerns: [:workable, :eventable]
      resources :references
      resources :relation_types, only: [:index, :show]
      resources :sources, concerns: [:workable, :eventable] do
        resources :months
      end
      resources :status, only: [:index]
      resources :work_types, only: [:index, :show]
      resources :works, constraints: { :id => /.+?/, :format=> false } do
        resources :references
        resources :versions
        resources :recommendations
        resources :events
      end
    end
  end

  # rescue routing errors
  match "*path", to: "alerts#routing_error", via: [:any]
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  attr_accessor :exception, :request

  belongs_to :source
  belongs_to :work

  before_create :collect_env_info, :create_uuid
  after_create :send_fatal_error_report, if: proc { level == 4 }

  default_scope { where("unresolved = ?", true).order("alerts.created_at DESC") }

  scope :errors, -> { where("alerts.level > ?", 1) }
  scope :query, ->(query) { includes(:work).where("class_name like ? OR message like ? OR status = ? OR works.pid = ?", "%#{query}%", "%#{query}%", query, "%#{query}%")
    .references(:work) }
  scope :total, ->(duration) { where("created_at > ?", Time.zone.now.beginning_of_day - duration.days) }
  scope :total_errors, ->(duration) { where("alerts.level > ?", 1).where("created_at > ?", Time.zone.now.beginning_of_day - duration.days) }
  scope :from_sources, ->(duration) { where("source_id IS NOT NULL").where("created_at > ?", Time.zone.now.beginning_of_day - duration.days) }

  # alert level, default is ERROR
  # adapted from http://www.ruby-doc.org/stdlib-2.1.2/libdoc/logger/rdoc/Logger.html
  LEVELS = %w(DEBUG INFO WARN ERROR FATAL)
  DEBUG  = 0
  INFO   = 1
  WARN   = 2
  ERROR  = 3
  FATAL  = 4

  def self.per_page
    15
  end

  def to_param
    uuid
  end

  def public_message
    case status
    when 404
      "The page you were looking for doesn't exist."
    else
      "Internal server error."
    end
  end

  def human_level_name
    LEVELS[level]
  end

  def send_fatal_error_report
    report = Report.where(name: 'fatal_error_report').first_or_create(
                          title: 'Fatal Error Report',
                          description: 'Reports when a fatal error has occured',
                          interval: 0,
                          private: true)
    report.send_fatal_error_report(message)
  end

  def create_date
    created_at.utc.iso8601
  end

  def create_uuid
    write_attribute(:uuid, SecureRandom.uuid)
  end

  private

  def collect_env_info
    # From https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/public_exceptions.rb and
    # http://www.sharagoz.com/posts/1-rolling-your-own-exception-handler-in-rails-3

    return false unless exception

    self.class_name     = class_name || exception.class.to_s
    self.message        = message || exception.message
    self.hostname       = hostname || ENV['HOSTNAME']

    if exception.is_a?(String)
      self.trace        = nil
    else
      trace             = exception.backtrace.map { |line| line.sub Rails.root.to_s, '' }
      self.trace        = trace.reject! { |line| line =~ /passenger|gems|ruby|synchronize/ }.join("\n")
    end

    if request
      self.remote_ip    = remote_ip || request.remote_ip
      self.user_agent   = user_agent || request.user_agent
      self.content_type = content_type || request.formats.first.to_s
      self.target_url   = target_url || request.original_url
    end

    self.source_id      = source_id if source_id
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_filter :load_alert, only: [:destroy]
  load_and_authorize_resource
  skip_authorize_resource :only => [:create, :routing_error]

  def index
    @servers = ENV['SERVERS'].split(",")

    collection = Alert
    if params[:source_id]
      collection = collection.includes(:source)
                   .where("sources.name = ?", params[:source_id])
                   .references(:source)
      @source = Source.where(name: params[:source_id]).first
    end

    if params[:hostname]
      collection = collection.where(:hostname => params[:hostname])
      @hostname = params[:hostname]
    end

    if params[:class_name]
      collection = collection.where(:class_name => params[:class_name])
      @class_name = params[:class_name]
    end

    if params[:level]
      level = Alert::LEVELS.index(params[:level].upcase) || 0
      collection = collection.where("level >= ?", level)
      @level = params[:level]
    end

    collection = collection.query(params[:q]) if params[:q]

    @alerts = collection.paginate(:page => params[:page])
  end

  def create
    exception = env["action_dispatch.exception"]
    @alert = Alert.where(message: exception.message).where(unresolved: true).first_or_initialize(
      :exception => exception,
      :request => request)

    # Filter for errors that should not be saved
    if ["ActiveRecord::RecordNotFound",
        "ActionController::RoutingError",
        "CustomError::TooManyRequestsError"].include?(exception.class.to_s)
      @alert.status = request.headers["PATH_INFO"][1..-1]
    else
      @alert.save
    end

    respond_to do |format|
      format.json { render json: { error: @alert.public_message }, status: @alert.status }
      format.html { render :show, status: @alert.status, layout: !request.xhr? }
    end
  end

  def destroy
    @servers = ENV['SERVERS'].split(",")
    if params[:filter] == "class_name"
      Alert.where(:class_name => @alert.class_name).update_all(:unresolved => false)
    elsif params[:filter] == "source"
      Alert.where(:source_id => @alert.source_id).update_all(:unresolved => false)
    elsif params[:filter] == "work_id"
      Alert.where(:work_id => @alert.work_id).update_all(:unresolved => false)
    else
      Alert.where(:message => @alert.message).update_all(:unresolved => false)
    end

    collection = Alert
    if params[:source_id]
      collection = collection.includes(:source)
                   .where("sources.name = ?", params[:source_id])
                   .references(:source)
      @source = Source.where(name: params[:source_id]).first
    end
    if params[:class_name]
      collection = collection.where(:class_name => params[:class_name])
      @class_name = params[:class_name]
    end
    if params[:work_id]
      collection = collection.where(:work_id => params[:work_id])
      @work = Work.where(id: params[:work_id]).first
    end
    collection = collection.query(params[:q]) if params[:q]

    @alerts = collection.paginate(:page => params[:page])

    if params[:work_id]
      render :alert
    else
      render :index
    end
  end

  def routing_error
    fail ActiveRecord::RecordNotFound
  end

  protected

  def load_alert
    @alert = Alert.where(uuid: params[:id]).first

    # raise error if source wasn't found
    fail ActiveRecord::RecordNotFound, "No record for \"#{params[:id]}\" found" if @alert.blank?
  end
end

app/controllers/api/v6/alerts_controller.rb
class Api::V6::AlertsController < Api::BaseController
  before_filter :authenticate_user_from_token!
  load_and_authorize_resource

  swagger_controller :alerts, "Alerts"

  swagger_api :index do
    summary "Returns all API alerts"
    notes "Authentication with a valid API key with staff or admin permissions is required."
    param :query, :unresolved, :boolean, :optional, "Return only unresolved alerts"
    param :query, :source_id, :string, :optional, "Source ID"
    param :query, :class_name, :string, :optional, "Class name of alert"
    param :query, :level, :integer, :optional, "Error level"
    param :query, :q, :string, :optional, "Query message or class name"
    param :query, :page, :integer, :optional, "Page number"
    response :ok
    response :unauthorized
    response :unprocessable_entity
    response :not_found
    response :internal_server_error
  end

  def index
    collection = Alert.unscoped.order("alerts.created_at DESC")
    collection = collection.where(unresolved: true) if params[:unresolved]
    if params[:source_id]
      collection = collection.joins(:source).where("sources.name = ?", params[:source_id])
      @source = Source.where(name: params[:source_id]).first
    end
    if params[:class_name]
      collection = collection.where(:class_name => params[:class_name])
      @class_name = params[:class_name]
    end
    if params[:level]
      level = Alert::LEVELS.index(params[:level].upcase) || 0
      collection = collection.where("level >= ?", level)
      @level = params[:level]
    end

    collection = collection.query(params[:q]) if params[:q]
    collection = collection.page(params[:page])
    per_page = params[:per_page] && (1..50).include?(params[:per_page].to_i) ? params[:per_page].to_i : 50
    collection = collection.per_page(per_page)
    @alerts = collection.decorate
  end
end

app/views/alerts/_index.html.erb
<div class="page-header">
  <div class="btn-toolbar pull-right">
    <div class="btn-group btn-group-sm">
      <%= link_to "#{icon("flag")} Filters".html_safe, filters_path, { id: "filters", class: "btn btn-default" } %>
    </div>
  </div>
  <h1 class="pull-left">
    <%= pluralize(@alerts.count, 'Alert') %>
  </h1>

  <%= form_tag(alerts_path, :method => "get", :class => "form-inline text-center", :role => "form") do %>
    <div class="form-group">
      <%= search_field_tag :q, params[:q], :placeholder => "Search", :class => "form-control" %>
    </div>
    <button type="submit" id="submit" class="btn btn-default hidden-xs"><%= icon("search") %></button>
    <% unless params[:q].blank? %>
      <%= link_to "clear", alerts_path(source_id: params[:source_id], class_name: params[:class_name], level: params[:level], hostname: params[:hostname]), class: "btn" %>
    <% end %>
  <% end %>
</div>

<div class="work">&nbsp;
  <div class="btn-toolbar pull-left">
    <% if @servers.length > 1 %>
      <div class="btn-group btn-group-sm">
        <a class="btn btn-default dropdown-toggle" id="hostname-menu" data-toggle="dropdown" href="#"><%= icon("filter") %> <%= @hostname.nil? ? "All Hosts" : @hostname %> <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All Hosts", alerts_path(class_name: params[:class_name], level: params[:level], q: params[:q]) %></li>
          <li class="divider"></li>
          <% @servers.each do |hostname| %>
            <li><%= link_to hostname, alerts_path(source_id: params[:source_id], class_name: params[:class_name], level: params[:level], hostname: hostname, q: params[:q]) %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="btn-group btn-group-sm">
      <a class="btn btn-default dropdown-toggle" id="source-menu" data-toggle="dropdown" href="#"><%= icon("filter") %> <%= @source.nil? ? "All Sources" : @source.title %> <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "All Sources", alerts_path(class_name: params[:class_name], level: params[:level], hostname: params[:hostname], q: params[:q]) %></li>
        <% Group.order("id").each do |group| %>
          <% unless group.sources.active.empty? %>
            <li class="divider"></li>
            <% group.sources.active.each do |source| %>
              <li><%= link_to h(source.title), alerts_path(source_id: source.name, class_name: params[:class_name], level: params[:level], hostname: params[:hostname], q: params[:q]) %></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div class="btn-group btn-group-sm">
      <a class="btn btn-default dropdown-toggle" id="level-menu" data-toggle="dropdown" href="#"><%= icon("filter") %> <%= @level.nil? ? "All Levels" : @level.titleize %> <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "All Levels", alerts_path(class_name: params[:class_name], source_id: params[:source_id], hostname: params[:hostname], q: params[:q]) %></li>
        <li class="divider"></li>
        <% Alert::LEVELS[1..-1].each do |level| %>
        <li><%= link_to h(level.titleize), alerts_path(level: level.downcase, class_name: params[:class_name], source_id: params[:source_id], hostname: params[:hostname], q: params[:q]) %></li>
        <% end %>
      </ul>
    </div>
    <div class="btn-group btn-group-sm">
      <a class="btn btn-default dropdown-toggle" id="alert-menu" data-toggle="dropdown" href="#"><%= icon("filter") %> <%= @class_name.nil? ? "All Alerts" : h(@class_name) %> <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "All Alerts", alerts_path(source_id: params[:source_id], level: params[:level], hostname: params[:hostname], q: params[:q]) %></li>
        <li class="divider"></li>
        <% alerts.each do |alert| %>
          <% if alert == "-" %>
            <li class="divider"></li>
          <% else %>
            <li><%= link_to h(alert), alerts_path(class_name: alert, source_id: params[:source_id], level: params[:level], hostname: params[:hostname], q: params[:q]) %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<% if @alerts.size > 0 %>
  <div class="panel-group" id="alert">
    <% @alerts.each do |alert| %>
      <div class="panel panel-default">
        <div class="panel-heading panel-title panel-list">
          <% if alert.level != 3 %><span class="pull-right"><%= level_label(alert.level).html_safe %></span><% end %>
          <%= link_to ((alert.status.blank? ? "" : "[#{alert.status}] ") + h(alert.message)).html_safe, "#alert_#{alert.uuid}", :class => "accordion-toggle", :id => "alert_#{alert.uuid}-link", :data => { :toggle => "collapse", :parent => "#alert" }, :href => "#alert_#{alert.uuid}" %>
        </div>
        <div class="panel-collapse collapse" id="alert_<%= alert.uuid %>">
          <div class="panel-body alert-inner">
            <% if can?(:destroy, Alert) %>
              <div class="btn-group btn-group-sm pull-right">
                <a class="btn btn-default dropdown-toggle" id="alert_<%= alert.uuid %>-delete" data-toggle="dropdown" href="#">
                  <%= icon("trash") %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "by Message", alert_path(alert, q: params[:q],
                                                                  source_id: params[:source_id],
                                                                  level: params[:level],
                                                                  class_name: params[:class_name],
                                                                  hostname: params[:hostname],
                                                                  page: params[:page]),
                                                                  method: :delete,
                                                                  data: { :confirm => 'Are you sure?' },
                                                                  remote: true,
                                                                  id: "alert_#{alert.uuid}-delete-message" %></li>
                  <li><%= link_to "by Class", alert_path(alert, q: params[:q],
                                                                source_id: params[:source_id],
                                                                level: params[:level],
                                                                class_name: params[:class_name],
                                                                hostname: params[:hostname],
                                                                filter: "class_name",
                                                                page: params[:page]),
                                                                method: :delete,
                                                                data: { :confirm => 'Are you sure?' },
                                                                remote: true,
                                                                id: "alert_#{alert.uuid}-delete-class" %></li>
                  <% unless alert.source_id.nil? %>
                    <li><%= link_to "by Source", alert_path(alert, q: params[:q],
                                                                   source_id: params[:source_id],
                                                                   level: params[:level],
                                                                   class_name: params[:class_name],
                                                                   hostname: params[:hostname],
                                                                   filter: "source",
                                                                   page: params[:page]),
                                                                   method: :delete,
                                                                   data: { :confirm => 'Are you sure?' },
                                                                   remote: true,
                                                                   id: "alert_#{alert.uuid}-delete-source" %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <p class="class-name"><%= link_to alert.class_name, alerts_path(class_name: h(alert.class_name),
                                                                            source_id: params[:source_id],
                                                                            level: params[:level],
                                                                            hostname: params[:hostname],
                                                                            q: params[:q]) %></p>
            <% if alert.source %>
              <h5>Source</h5>
              <%= link_to alert.source.title, source_path(alert.source) %>
            <% end %>

            <% if alert.work %>
              <h5>Work</h5>
              <%= link_to alert.work.pid, work_path(alert.work) %>
            <% end %>

            <h5>Time</h5>
            <%= alert.created_at.to_s(:friendly) %>

            <% unless alert.hostname.blank? %>
              <h5>Hostname</h5>
              <%= alert.hostname %>
            <% end %>

            <% unless alert.content_type.blank? or alert.content_type == "text/html" %>
              <h5>Content Type</h5>
              <%= alert.content_type %>
            <% end %>

            <% unless alert.target_url.blank? %>
              <h5>Target URL</h5>
              <%= link_to alert.target_url, alert.target_url %>
            <% end %>

            <% if ["Net::HTTPUnauthorized","ActionDispatch::RemoteIp::IpSpoofAttackError"].include? alert.class_name %>
              <% unless alert.remote_ip.blank? %>
                <h5>Remote IP</h5>
                <%= link_to alert.remote_ip, alert.remote_ip %>
              <% end %>

              <% unless alert.user_agent.blank? %>
                <h5>User Agent</h5>
                <%= alert.user_agent %>
              <% end %>
            <% end %>

            <% unless alert.details.blank? %>
              <h5>Details</h5>
              <%= alert.details %>
            <% end %>

            <% unless alert.trace.blank? %>
              <h5>Trace</h5>
              <%= simple_format(alert.trace) %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="text-center">
    <%= will_paginate @alerts, :params => { :controller => alerts_path }, :renderer => BootstrapPagination::Rails %>
  </div>
<% else %>
  <div class="alert alert-info">There are currently no <% unless @class_name.nil? %><%= h(@class_name) %> <% end %>alerts
    <% unless @source.nil? %>
      for <%= @source.title %>
    <% end %>
    <% unless @level.nil? %>
      with at least level <em><%= @level.titleize %></em>
    <% end %>
    <% unless params[:q].blank? %>
      with <em><%= params[:q] %></em> in the class name, message or PID
    <% end %>
  </div>
<% end %>

app/views/alerts/alert.js.erb
$('#alert-error-message').html("<%= escape_javascript(render "works/alert_message") %>");
$('#alert').html("<%= escape_javascript(render "works/alert") %>");

app/views/alerts/index.html.erb
<div class="content" id="index">
  <%= render :partial => 'index' %>
</div>

app/views/alerts/index.js.erb
$('#index').html("<%= escape_javascript(render "index") %>");

app/views/alerts/show.html.erb
<div class="content">
  <div class="alert alert-warning"><b><%= @alert.status %></b> <%= @alert.message %></div>
</div>