config/routes.rb
require 'sidekiq/web'

Lagotto::Application.routes.draw do
  # mount EmberCLI::Engine => "ember-tests" if Rails.env.development?

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  #root :to => "ember#index"
  #get '/docs/*path' => 'ember#index'

  # simplify GET route to works
  #get '/:id', to: 'works#show', constraints: { id: /(http|https):\/\/.+/, format: /html/ }
  root :to => "docs#index"

  resources :alerts
  resources :api_requests
  resources :docs, :only => [:index, :show], :constraints => { :id => /[0-z\-\.\(\)]+/ }
  resources :filters
  resources :publishers
  resources :references

  # use namespace for rss feeds rather than file extension
  namespace :rss, defaults: { format: "rss" } do
    resources :works, constraints: { :id => /.+/ }, only: [:show]
    resources :sources, only: [:show]
  end

  # redirect old rss routes
  get '/sources/:id.rss', to: redirect { |params, request| "/rss/sources/#{request.params[:id]}?#{request.params.to_query}" }

  resources :sources do
    resources :publisher_options, only: [:show, :edit, :update]
  end
  resources :status, :only => [:index]
  resources :users

  # constraints is added to allow dot in the url (doi is used to show article)
  resources :works, constraints: { :id => /.+/, :format => /html|js/ }

  get "oembed", to: "oembed#show"

  get "/files/alm_report.zip", to: redirect("/files/alm_report.zip")
  get "/api", to: "api/index#index"

  namespace :api, defaults: { format: "json" } do
    namespace :v3 do
      resources :works, path: "articles", constraints: { :id => /.+?/, :format=> false }, only: [:index, :show]
    end

    namespace :v5 do
      resources :works, path: "articles", constraints: { :id => /.+?/ }, only: [:index]
      resources :sources, only: [:index, :show]
      resources :status, only: [:index]
      resources :api_requests, only: [:index]
      resources :publishers, only: [:index]
    end

    scope module: :v6, constraints: ApiConstraint.new(version: 6, default: :true) do
      concern :workable do
        resources :works, constraints: { :id => /.+?/, format: false }
      end

      concern :eventable do
        resources :events
      end

      resources :alerts
      resources :api_requests, only: [:index]
      resources :docs, only: [:index, :show]
      resources :events
      resources :groups, only: [:index, :show]
      resources :publishers, concerns: [:workable, :eventable]
      resources :references
      resources :relation_types, only: [:index, :show]
      resources :sources, concerns: [:workable, :eventable] do
        resources :months
      end
      resources :status, only: [:index]
      resources :work_types, only: [:index, :show]
      resources :works, constraints: { :id => /.+?/, :format=> false } do
        resources :references
        resources :versions
        resources :recommendations
        resources :events
      end
    end
  end

  # rescue routing errors
  match "*path", to: "alerts#routing_error", via: [:any]
end

app/models/status.rb
class Status < ActiveRecord::Base
  # include HTTP request helpers
  include Networkable

  RELEASES_URL = "https://api.github.com/repos/articlemetrics/lagotto/releases"

  before_create :collect_status_info, :create_uuid

  default_scope { order("status.created_at DESC") }

  def self.per_page
    1000
  end

  def to_param
    uuid
  end

  def collect_status_info
    self.works_count = Work.tracked.count
    self.works_new_count = Work.tracked.last_x_days(0).count
    self.events_count = RetrievalStatus.joins(:source).where("state > ?", 0)
      .where("name != ?", "relativemetric").sum(:total)
    self.responses_count = ApiResponse.total(1).count
    self.requests_count = ApiRequest.total(1).count
    self.requests_average = ApiRequest.total(1).average("duration").to_i
    self.alerts_count = Alert.total_errors(0).count
    self.db_size = get_db_size
    self.sources_working_count = Source.working.count
    self.sources_waiting_count = Source.waiting.count
    self.sources_disabled_count = Source.disabled.count
    self.version = Lagotto::VERSION
    self.current_version = get_current_version unless current_version.present?
  end

  def sources
    { "working" => sources_working_count,
      "waiting" => sources_waiting_count,
      "disabled" => sources_disabled_count }
  end

  def get_current_version
    result = get_result(RELEASES_URL)
    result = result.is_a?(Array) ? result.first : {}
    result.fetch("tag_name", "v.#{version}")[2..-1]
  end

  # get combined data and index size for all tables
  def get_db_size
    sql = "SELECT SUM(DATA_LENGTH + INDEX_LENGTH) as size FROM information_schema.TABLES where TABLE_SCHEMA = '#{ENV['DB_NAME'].to_s}';"
    result = ActiveRecord::Base.connection.exec_query(sql)
    result.rows.first.reduce(:+)
  end

  def outdated_version?
    Gem::Version.new(current_version) > Gem::Version.new(version)
  end

  def services_ok?
    # web, mysql and memcached must be running if you can see services panel on status page
    if redis == "OK" && sidekiq == "OK" && postfix == "OK"
      true
    else
      false
    end
  end

  def redis
    redis_client = Redis.new
    redis_client.ping == "PONG" ? "OK" : "failed"
  rescue
    "failed"
  end

  def sidekiq
    sidekiq_client = Sidekiq::ProcessSet.new
    sidekiq_client.size > 0 ? "OK" : "failed"
  rescue
    "failed"
  end

  def postfix
    Timeout::timeout(3) do
      Net::SMTP.start(ENV["MAIL_ADDRESS"], ENV["MAIL_PORT"])
    end
    "OK"
  rescue
    "failed"
  end

  def timestamp
    updated_at.utc.iso8601
  end

  def create_uuid
    write_attribute(:uuid, SecureRandom.uuid)
  end
end

app/controllers/api/v6/status_controller.rb
class Api::V6::StatusController < Api::BaseController
  before_filter :authenticate_user_from_token!

  swagger_controller :status, "Status"

  swagger_api :index do
    summary "Returns status information"
    notes "Status information is generated every hour. Returns 1,000 results per page."
    param :query, :page, :integer, :optional, "Page number"
    response :ok
    response :unprocessable_entity
    response :not_found
  end

  def index
    Status.create unless Status.count > 0

    collection = Status.all.order("created_at DESC").paginate(:page => params[:page])
    @status = collection.decorate(context: { role: is_admin_or_staff? })
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def index
    Status.create(current_version: Lagotto::VERSION) if Rails.env == "development" || Status.count == 0

    collection = Status.order("created_at DESC")
    @current_status = collection.first
    @status = collection.paginate(:page => params[:page])

    @process = SidekiqProcess.new

    if current_user.try(:is_admin?) && @current_status.outdated_version?
      flash.now[:alert] = "Your Lagotto software is outdated, please install <a href='https://github.com/articlemetrics/lagotto/releases'>version #{@current_status.current_version}</a>.".html_safe
      @flash = flash
    end
  end

  private

  def safe_params
    params.require(:status).permit(:current_version)
  end
end

app/views/status/index.html.erb
<div class="page-header">
  <h1 id="api_key" data-api_key="<%= current_user && current_user.api_key %>">Status <small id="timestamp"><%= date_from_iso8601(@current_status.timestamp) + ' UTC' %></small></h1>
</div>

<div class="content">
  <div class="row">
  <div class="col-md-4">
    <div class="panel <%= @current_status.works_count > 0 ? 'panel-default' : 'panel-warning' %>">
      <div class="panel-heading">Works</div>
      <div class="panel-body panel-chart">
        <h2 class="graphs"><%= link_to_if @current_status.works_count > 0, number_with_delimiter(@current_status.works_count), works_path %></h2>
        <div class="graphs" id="chart_works"></div>
        <div class="text-muted" id="chart_works-loading">Loading … <%= image_tag "spinner.gif" %></div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel <%= @current_status.events_count > 0 ? 'panel-default' : 'panel-warning' %>">
      <div class="panel-heading">Events</div>
      <div class="panel-body panel-chart">
        <h2 class="graphs"><%= link_to_if @current_status.events_count > 0, number_with_delimiter(@current_status.events_count), sources_path %></h2>
        <div class="graphs" id="chart_events"></div>
        <div class="text-muted" id="chart_events-loading">Loading … <%= image_tag "spinner.gif" %></div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel <%= @current_status.sources_disabled_count > 0 ? 'panel-warning' : 'panel-default' %>">
      <div class="panel-heading">Sources</div>
      <div class="panel-body panel-chart" id="chart_sources">
        <div class="text-muted" id="chart_sources-loading">Loading … <%= image_tag "spinner.gif" %></div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel <%= @current_status.responses_count > 0 ? 'panel-default' : 'panel-warning' %>">
      <div class="panel-heading">API responses <small class="pull-right">last hour</small></div>
      <div class="panel-body panel-chart">
        <h2 class="graphs"><%= link_to_if @current_status.responses_count > 0, number_with_delimiter(@current_status.responses_count), sources_path %></h2>
        <div class="graphs" id="chart_responses"></div>
        <div class="text-muted" id="chart_responses-loading">Loading … <%= image_tag "spinner.gif" %></div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel <%= @current_status.requests_count > 0 ? 'panel-default' : 'panel-warning' %>">
      <div class="panel-heading">API requests <small class="pull-right">last hour</small></div>
      <div class="panel-body panel-chart">
        <h2 class="graphs"><%= link_to_if @current_status.requests_count > 0, number_with_delimiter(@current_status.requests_count), api_requests_path %></h2>
        <div class="graphs" id="chart_requests"></div>
        <div class="text-muted" id="chart_requests-loading">Loading … <%= image_tag "spinner.gif" %></div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel <%= @current_status.requests_average > 0 ? 'panel-default' : 'panel-warning' %>">
      <div class="panel-heading">API requests (average) <small class="pull-right">last hour</small></div>
      <div class="panel-body panel-chart">
        <h2 class="graphs"><%= link_to_if @current_status.requests_average > 0, number_with_delimiter(@current_status.requests_average) + " ms", api_requests_path %></h2>
        <div class="graphs" id="chart_average"></div>
        <div class="text-muted" id="chart_average-loading">Loading … <%= image_tag "spinner.gif" %></div>
      </div>
    </div>
  </div>
</div>

<% if can?(:read, Alert) %>
  <div class="row">
    <div class="col-md-4">
      <div class="panel <%= @current_status.alerts_count > 0 ? 'panel-default' : 'panel-success' %>">
        <div class="panel-heading">Unresolved alerts</div>
        <div class="panel-body panel-chart">
          <h2 class="graphs"><%= link_to_if @current_status.alerts_count > 0, number_with_delimiter(@current_status.alerts_count), alerts_path %></h2>
          <div class="graphs" id="chart_alerts"></div>
          <div class="text-muted" id="chart_alerts-loading">Loading … <%= image_tag "spinner.gif" %></div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel <%= @current_status.db_size > 0 ? 'panel-default' : 'panel-warning' %>">
        <div class="panel-heading">Database size</div>
        <div class="panel-body panel-chart text-center">
          <h2 class="graphs" id="db_size"><%= number_to_human_size(@current_status.db_size) %></h2>
          <div class="graphs" id="chart_db_size"></div>
          <div class="text-muted" id="chart_db_size-loading">Loading … <%= image_tag "spinner.gif" %></div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel <%= @current_status.outdated_version? ? 'panel-warning' : 'panel-default' %>">
        <div class="panel-heading">Lagotto version</div>
        <div class="panel-body panel-chart text-center">
          <h2 class="graphs" id="version"><%= @current_status.version %></h2>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel <%= worker_label(@process.current_status) %>">
        <div class="panel-heading">Jobs</div>
        <table class="table">
          <thead>
            <tr>
              <th class="jobs">Processed</th>
              <th class="jobs">Failed</th>
              <th class="jobs">Busy</th>
              <th class="jobs">Enqueued</th>
              <th class="jobs">Retries</th>
              <th class="jobs">Scheduled</th>
              <th class="jobs">Dead</th>
            </tr>
          </thead>
          <tbody>
            <tr>
            <% if can?(:manage, Alert) %>
              <td class="jobs"><%= link_to_if @process.stats.processed > 0, number_with_delimiter(@process.stats.processed), sidekiq_web_path, target: "_blank" %></td>
              <td class="jobs"><%= link_to_if @process.stats.failed > 0, number_with_delimiter(@process.stats.failed), sidekiq_web_path, target: "_blank" %></td>
              <td class="jobs"><%= link_to_if @process.workers_size > 0, number_with_delimiter(@process.workers_size), "/sidekiq/busy", target: "_blank" %></td>
              <td class="jobs"><%= link_to_if @process.stats.enqueued > 0, number_with_delimiter(@process.stats.enqueued), "/sidekiq/queues", target: "_blank" %></td>
              <td class="jobs"><%= link_to_if @process.stats.retry_size > 0, number_with_delimiter(@process.stats.retry_size), "/sidekiq/retries", target: "_blank" %></td>
              <td class="jobs"><%= link_to_if @process.stats.scheduled_size > 0, number_with_delimiter(@process.stats.scheduled_size), "/sidekiq/scheduled", target: "_blank" %></td>
              <td class="jobs"><%= link_to_if @process.stats.dead_size > 0, number_with_delimiter(@process.stats.dead_size), "/sidekiq/morgue", target: "_blank" %></td>
            <% else %>
              <td class="jobs"><%= number_with_delimiter(@process.stats.processed) %></td>
              <td class="jobs"><%= number_with_delimiter(@process.stats.failed) %></td>
              <td class="jobs"><%= number_with_delimiter(@process.workers_size) %></td>
              <td class="jobs"><%= number_with_delimiter(@process.stats.enqueued) %></td>
              <td class="jobs"><%= number_with_delimiter(@process.stats.retry_size) %></td>
              <td class="jobs"><%= number_with_delimiter(@process.stats.scheduled_size) %></td>
              <td class="jobs"><%= number_with_delimiter(@process.stats.dead_size) %></td>
            <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>
</div>

<%= javascript_include_tag 'status/index' %>